/**
    This file was generated by FSMViewerAvalonia (https://github.com/HKLab/FSMViewAvalonia).
    Generator Type: FSMViewAvalonia2.CodeGen.FsmProxy.DefaultFsmProxy
    **/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using HutongGames.PlayMaker;

namespace FSMProxy;

internal class FSMProxy_SoulMaster
{
    public static class StateNames
    {
        public const string Init = "Init";
        public const string Idle = "Idle";
        public const string Teleport = "Teleport";
        public const string Tele_Line = "Tele Line";
        public const string Tele_Away = "Tele Away";
        public const string Pause = "Pause";
        public const string Away_Valid = "Away Valid?";
        public const string Tele_Top_Y = "Tele Top Y";
        public const string Tele_Spinner_X = "Tele Spinner X";
        public const string After_Tele = "After Tele";
        public const string HS_Summon = "HS Summon";
        public const string HS_Orb = "HS Orb";
        public const string HS_Dir = "HS Dir";
        public const string HS_Right = "HS Right";
        public const string HS_Left = "HS Left";
        public const string HS_Stop = "HS Stop";
        public const string HS_Tele_Out = "HS Tele Out";
        public const string HS_Ret_Left = "HS Ret Left";
        public const string Hs_Ret_Right = "Hs Ret Right";
        public const string Reactivate = "Reactivate";
        public const string HS_Dissipate = "HS Dissipate";
        public const string Tele_Charge = "Tele Charge";
        public const string Charge_Dir = "Charge Dir";
        public const string Charge_Left = "Charge Left";
        public const string Charge_Right = "Charge Right";
        public const string Charge_Stop = "Charge Stop";
        public const string Tele_Bot_Y = "Tele Bot Y";
        public const string Set_Shots = "Set Shots";
        public const string Shot_Antic = "Shot Antic";
        public const string Shot = "Shot";
        public const string Tele_Shoot = "Tele Shoot";
        public const string Attack_Choice = "Attack Choice";
        public const string Next = "Next?";
        public const string Damaged_Idle = "Damaged Idle";
        public const string Set_Idle_Timer = "Set Idle Timer";
        public const string Shoot_Valid = "Shoot Valid?";
        public const string Tele_Quake = "Tele Quake";
        public const string TeleportQ = "TeleportQ";
        public const string Tele_Line_Q = "Tele Line Q";
        public const string Quake_Antic = "Quake Antic";
        public const string Quake_Down = "Quake Down";
        public const string Quake_Land = "Quake Land";
        public const string Re_Pos = "Re Pos";
        public const string Quake_Waves = "Quake Waves";
        public const string Damage_Tele_Away = "Damage Tele Away";
        public const string Attack_Instead = "Attack Instead";
        public const string Charge_Antic = "Charge Antic";
        public const string Fakeout = "Fakeout?";
        public const string Fake_Down = "Fake Down";
        public const string Reset = "Reset";
        public const string Stun_Init = "Stun Init";
        public const string Stun_L = "Stun L";
        public const string Stun_R = "Stun R";
        public const string Stun_Start_1 = "Stun Start 1";
        public const string Stun_Start_2 = "Stun Start 2";
        public const string Stunned = "Stunned";
        public const string Stun_Reset = "Stun Reset";
        public const string Stun_Hit = "Stun Hit";
        public const string Stun_Hit_L = "Stun Hit L";
        public const string Stun_Hit_R = "Stun Hit R";
        public const string Sleep = "Sleep";
        public const string Set_Entry_Point = "Set Entry Point";
        public const string Teleport_In = "Teleport In";
        public const string Roar = "Roar";
        public const string Roar_End = "Roar End";
        public const string Encountered = "Encountered?";
        public const string Quick_Start = "Quick Start";
        public const string Music = "Music";
        public const string GG_Enter = "GG Enter";
    }
    public static class VariableNames
    {
        public const string Dmg_Tele_Away = "Dmg Tele Away";
        public const string Done_Quake = "Done Quake";
        public const string Faked = "Faked";
        public const string High_Spinner_Right = "High Spinner Right";
        public const string Start_Range = "Start Range";
        public const string Angle = "Angle";
        public const string Bot_Y = "Bot Y";
        public const string Distance = "Distance";
        public const string Final_Tele_Distance = "Final Tele Distance";
        public const string Ground_Y = "Ground Y";
        public const string Hero_Mid_X = "Hero Mid X";
        public const string Hero_X = "Hero X";
        public const string Hero_Y = "Hero Y";
        public const string High_Spinner_Speed = "High Spinner Speed";
        public const string Idle_Timer = "Idle Timer";
        public const string Knight_Quake_Y_Max = "Knight Quake Y Max";
        public const string Left_X = "Left X";
        public const string Move_Speed = "Move Speed";
        public const string Quake_Speed = "Quake Speed";
        public const string Quake_Y = "Quake Y";
        public const string Random = "Random";
        public const string Right_X = "Right X";
        public const string Self_X = "Self X";
        public const string Self_Y = "Self Y";
        public const string Self_Z = "Self Z";
        public const string Shockwave_Height = "Shockwave Height";
        public const string Shockwave_Speed = "Shockwave Speed";
        public const string Shockwave_Y = "Shockwave Y";
        public const string Shot_Speed = "Shot Speed";
        public const string Speed_Crt = "Speed Crt";
        public const string Tele_Angle = "Tele Angle";
        public const string Tele_X = "Tele X";
        public const string Tele_Y = "Tele Y";
        public const string Top_Y = "Top Y";
        public const string X_Scale = "X Scale";
        public const string Appear_Flash = "Appear Flash";
        public const string Area_Title = "Area Title";
        public const string Arrive_Particles = "Arrive Particles";
        public const string CamLock = "CamLock";
        public const string Fire_Effect = "Fire Effect";
        public const string Head_Box = "Head Box";
        public const string Orb_Spinner = "Orb Spinner";
        public const string Projectile = "Projectile";
        public const string Quake_Blast = "Quake Blast";
        public const string Quake_Box = "Quake Box";
        public const string Quake_Hit = "Quake Hit";
        public const string Quake_Particles = "Quake Particles";
        public const string Quake_Pillar = "Quake Pillar";
        public const string Quake_Rocks = "Quake Rocks";
        public const string Roar_Emitter = "Roar Emitter";
        public const string Self = "Self";
        public const string Shockwave = "Shockwave";
        public const string Shot_Charge = "Shot Charge";
        public const string Silh_Charge = "Silh Charge";
        public const string Silh_Flash = "Silh Flash";
        public const string Silhouette = "Silhouette";
        public const string Tele_Line = "Tele Line";
        public const string Tele_Out_Anim = "Tele Out Anim";
        public const string Voice_Player = "Voice Player";
        public const string Weak_Particles = "Weak Particles";
        public const string White_Flash = "White Flash";
        public const string Wound_Box = "Wound Box";
        public const string Ct_Charge = "Ct Charge";
        public const string Ct_HS = "Ct HS";
        public const string Ct_Quake = "Ct Quake";
        public const string Ct_Shoot = "Ct Shoot";
        public const string Ms_Charge = "Ms Charge";
        public const string Ms_HS = "Ms HS";
        public const string Ms_Quake = "Ms Quake";
        public const string Ms_Shoot = "Ms Shoot";
        public const string Shots = "Shots";
        public const string Next_Event = "Next Event";
        public const string Hero_Pos = "Hero Pos";
        public const string Line_Pos = "Line Pos";
        public const string Self_Pos = "Self Pos";
        public const string Teleport_Point = "Teleport Point";
    }
    public static class EventNames
    {
        public const string FINISHED = "FINISHED";
        public const string ATTACK = "ATTACK";
        public const string CANCEL = "CANCEL";
        public const string CHARGE = "CHARGE";
        public const string FAKE = "FAKE";
        public const string GG_BOSS = "GG BOSS";
        public const string HIGH_SPINNER = "HIGH SPINNER";
        public const string IDLE = "IDLE";
        public const string LEFT = "LEFT";
        public const string QUAKE = "QUAKE";
        public const string REDO = "REDO";
        public const string REFIGHT = "REFIGHT";
        public const string RIGHT = "RIGHT";
        public const string ROAR = "ROAR";
        public const string SHOOT = "SHOOT";
        public const string STUN = "STUN";
        public const string TELE_AWAY = "TELE AWAY";
        public const string TOOK_DAMAGE = "TOOK DAMAGE";
        public const string WAKE = "WAKE";
    }
    public class FsmVariablesHolder
    {
        public FsmVariables fsmVariables;
        public FsmBool Dmg_Tele_Away
        {
            get
            {
                return fsmVariables.FindFsmBool(VariableNames.Dmg_Tele_Away);
            }
        }
        public FsmBool Done_Quake
        {
            get
            {
                return fsmVariables.FindFsmBool(VariableNames.Done_Quake);
            }
        }
        public FsmBool Faked
        {
            get
            {
                return fsmVariables.FindFsmBool(VariableNames.Faked);
            }
        }
        public FsmBool High_Spinner_Right
        {
            get
            {
                return fsmVariables.FindFsmBool(VariableNames.High_Spinner_Right);
            }
        }
        public FsmBool Start_Range
        {
            get
            {
                return fsmVariables.FindFsmBool(VariableNames.Start_Range);
            }
        }
        public FsmFloat Angle
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Angle);
            }
        }
        public FsmFloat Bot_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Bot_Y);
            }
        }
        public FsmFloat Distance
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Distance);
            }
        }
        public FsmFloat Final_Tele_Distance
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Final_Tele_Distance);
            }
        }
        public FsmFloat Ground_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Ground_Y);
            }
        }
        public FsmFloat Hero_Mid_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hero_Mid_X);
            }
        }
        public FsmFloat Hero_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hero_X);
            }
        }
        public FsmFloat Hero_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hero_Y);
            }
        }
        public FsmFloat High_Spinner_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.High_Spinner_Speed);
            }
        }
        public FsmFloat Idle_Timer
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Idle_Timer);
            }
        }
        public FsmFloat Knight_Quake_Y_Max
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Knight_Quake_Y_Max);
            }
        }
        public FsmFloat Left_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Left_X);
            }
        }
        public FsmFloat Move_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Move_Speed);
            }
        }
        public FsmFloat Quake_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Quake_Speed);
            }
        }
        public FsmFloat Quake_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Quake_Y);
            }
        }
        public FsmFloat Random
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Random);
            }
        }
        public FsmFloat Right_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Right_X);
            }
        }
        public FsmFloat Self_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Self_X);
            }
        }
        public FsmFloat Self_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Self_Y);
            }
        }
        public FsmFloat Self_Z
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Self_Z);
            }
        }
        public FsmFloat Shockwave_Height
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Shockwave_Height);
            }
        }
        public FsmFloat Shockwave_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Shockwave_Speed);
            }
        }
        public FsmFloat Shockwave_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Shockwave_Y);
            }
        }
        public FsmFloat Shot_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Shot_Speed);
            }
        }
        public FsmFloat Speed_Crt
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Speed_Crt);
            }
        }
        public FsmFloat Tele_Angle
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Tele_Angle);
            }
        }
        public FsmFloat Tele_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Tele_X);
            }
        }
        public FsmFloat Tele_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Tele_Y);
            }
        }
        public FsmFloat Top_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Top_Y);
            }
        }
        public FsmFloat X_Scale
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.X_Scale);
            }
        }
        public FsmGameObject Appear_Flash
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Appear_Flash);
            }
        }
        public FsmGameObject Area_Title
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Area_Title);
            }
        }
        public FsmGameObject Arrive_Particles
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Arrive_Particles);
            }
        }
        public FsmGameObject CamLock
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.CamLock);
            }
        }
        public FsmGameObject Fire_Effect
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Fire_Effect);
            }
        }
        public FsmGameObject Head_Box
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Head_Box);
            }
        }
        public FsmGameObject Orb_Spinner
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Orb_Spinner);
            }
        }
        public FsmGameObject Projectile
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Projectile);
            }
        }
        public FsmGameObject Quake_Blast
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Quake_Blast);
            }
        }
        public FsmGameObject Quake_Box
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Quake_Box);
            }
        }
        public FsmGameObject Quake_Hit
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Quake_Hit);
            }
        }
        public FsmGameObject Quake_Particles
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Quake_Particles);
            }
        }
        public FsmGameObject Quake_Pillar
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Quake_Pillar);
            }
        }
        public FsmGameObject Quake_Rocks
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Quake_Rocks);
            }
        }
        public FsmGameObject Roar_Emitter
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Roar_Emitter);
            }
        }
        public FsmGameObject Self
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Self);
            }
        }
        public FsmGameObject Shockwave
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Shockwave);
            }
        }
        public FsmGameObject Shot_Charge
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Shot_Charge);
            }
        }
        public FsmGameObject Silh_Charge
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Silh_Charge);
            }
        }
        public FsmGameObject Silh_Flash
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Silh_Flash);
            }
        }
        public FsmGameObject Silhouette
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Silhouette);
            }
        }
        public FsmGameObject Tele_Line
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Tele_Line);
            }
        }
        public FsmGameObject Tele_Out_Anim
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Tele_Out_Anim);
            }
        }
        public FsmGameObject Voice_Player
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Voice_Player);
            }
        }
        public FsmGameObject Weak_Particles
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Weak_Particles);
            }
        }
        public FsmGameObject White_Flash
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.White_Flash);
            }
        }
        public FsmGameObject Wound_Box
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Wound_Box);
            }
        }
        public FsmInt Ct_Charge
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Charge);
            }
        }
        public FsmInt Ct_HS
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_HS);
            }
        }
        public FsmInt Ct_Quake
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Quake);
            }
        }
        public FsmInt Ct_Shoot
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Shoot);
            }
        }
        public FsmInt Ms_Charge
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_Charge);
            }
        }
        public FsmInt Ms_HS
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_HS);
            }
        }
        public FsmInt Ms_Quake
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_Quake);
            }
        }
        public FsmInt Ms_Shoot
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_Shoot);
            }
        }
        public FsmInt Shots
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Shots);
            }
        }
        public FsmString Next_Event
        {
            get
            {
                return fsmVariables.FindFsmString(VariableNames.Next_Event);
            }
        }
        public FsmVector3 Hero_Pos
        {
            get
            {
                return fsmVariables.FindFsmVector3(VariableNames.Hero_Pos);
            }
        }
        public FsmVector3 Line_Pos
        {
            get
            {
                return fsmVariables.FindFsmVector3(VariableNames.Line_Pos);
            }
        }
        public FsmVector3 Self_Pos
        {
            get
            {
                return fsmVariables.FindFsmVector3(VariableNames.Self_Pos);
            }
        }
        public FsmVector3 Teleport_Point
        {
            get
            {
                return fsmVariables.FindFsmVector3(VariableNames.Teleport_Point);
            }
        }
    }
    public Fsm FSM { get; }
    public FsmVariablesHolder Variables { get; }
    public FSMProxy_SoulMaster(Fsm fsm)
    {
        this.FSM = fsm;
        this.Variables = new FsmVariablesHolder();
        this.Variables.fsmVariables = fsm.Variables;
    }
    public FSMProxy_SoulMaster(PlayMakerFSM fsm) : this(fsm.Fsm) { }
}
